theme: jekyll-theme-minimal
title: Devraj's Profile
description: Website to showcase my profile.
author: Devraj
email: devraj@example.com
repository: https://github.com/devrajgoswami/devrajgoswami.github.io